# Generated by Django 4.1.7 on 2023-10-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_category_tb'),
        ('seller', '0002_seller_table_delete_selller_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.FileField(max_length=20, upload_to='')),
                ('price', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=20)),
                ('stock', models.IntegerField(max_length=20)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.category_tb')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller_table')),
            ],
        ),
    ]
