# Generated by Django 4.1.7 on 2023-10-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
