# Generated by Django 4.1.7 on 2023-11-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_tracking_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking_table',
            old_name='order_id',
            new_name='orderid',
        ),
    ]
