# Generated by Django 4.1.7 on 2023-10-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_register_table_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='DOB',
            field=models.CharField(max_length=20),
        ),
    ]
