# Generated by Django 4.1.7 on 2023-10-27 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_product_table_stock'),
        ('buyer', '0003_alter_register_table_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(max_length=20)),
                ('total', models.IntegerField(max_length=20)),
                ('buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.register_table')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product_table')),
            ],
        ),
    ]
