# Generated by Django 4.1.7 on 2023-10-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_cart_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_table',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart_table',
            name='total',
            field=models.IntegerField(),
        ),
    ]
