# Generated by Django 4.1.7 on 2023-11-02 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_oderitems_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=20)),
                ('cardnumber', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=20)),
                ('expiary_date', models.CharField(max_length=20)),
                ('buyerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.register_table')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.order_table')),
            ],
        ),
    ]
